### PR TITLE
Use a pure golang pcr extend

### PR DESCRIPTION
**Pull request by Itxaka**
Instead of using systemd-pcrphase/pcrextend

### CODE REVIEW

**Review by mauromorales — APPROVED** [review]
fancy 😎

**Comment by mudler** [comment]
did you tried if they are compatible? e.g. are they returning the same measurements? 

otherwise this should be marked for a breaking change or offer the native implementation under a switch

**Comment by mudler** [comment]
also I wonder if we can re-use pcrlock as well, so we don't need to depend on a specific systemd version to bind to lower PCR banks

**Comment by Itxaka** [comment]
yep, upgrade went fine as well, partitions locked with systemd-pcrextend were unlocked with the golang reimplementation

**Comment by Itxaka** [comment]
@mudler do you want to keep this under a feature flag? or can we merge it as is?

**Comment by mudler** [comment]
no need to put a feature flag if we are sure it does not break `systemd-> golang`. Thanks for double-checking!

**Pull request merged**
